site_name: Darrin DeYoung 的笔记本
site_url: https://darrindeyoung791.github.io/blog/
repo_name: darrindeyoung791/blog
repo_url: https://github.com/darrindeyoung791/blog/
site_description: Darrin DeYoung 的笔记本
copyright: Copyright &copy; 2025 <a href="https://github.com/darrindeyoung791" target="_blank" rel="noopener">darrindeyoung791</a> <br> 如无特殊说明，本站全部内容在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" target="_blank" rel="noopener">CC-BY-SA 4.0</a> 协议之条款下提供

theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.select

  name: material
  language: zh 
  palette:
    # 自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darrindeyoung791

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: zh
      timezone: Asia/Shanghai
