name: Deploy MkDocs
on:
  push:
    branches: 
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整git历史
          sparse-checkout: |
            docs
            .github
            mkdocs.yml
            requirements.txt
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 指定具体的Python版本
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
